(() => {
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let type='system',drafts=[],current=null,loaded=false;
const sections={system:['pumpset','control_panel','manifold','tank','misc'],pumpset:['pump','motor','coupling','baseplate']};
const labels={pumpset:'Pumpset',control_panel:'Control Panel',manifold:'Manifold',tank:'Tank',misc:'MISC',pump:'Pump',motor:'Motor',coupling:'Coupling',baseplate:'Baseplate'};
const key=()=>`ks_v201_assembly_${window.KEYSUITE_PROFILE?.company_id||'company'}`;
const uid=()=>crypto.randomUUID?.()||`asm-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const customers=()=>window.KeySuiteApp?.getCustomers?.()||[];
function quoteCustomerId(){return window.KeySuiteApp?.getPricingCustomerId?.()||''}
function blank(t=type){return {id:uid(),assembly_type:t,model_item:'',description:'',name:t==='system'?'New System':'New Pumpset',customer_id:quoteCustomerId(),status:'draft',items:[],created_at:new Date().toISOString(),updated_at:new Date().toISOString()}}
function normalize(d){d={...blank(d?.assembly_type||type),...d};d.items=(d.items||[]).map(x=>({...x,section:x.section||defaultSection(d.assembly_type,x)}));return d}
function defaultSection(t,item){if(t==='pumpset')return item?.section||'pump';return item?.section||'misc'}
function localLoad(){try{return (JSON.parse(localStorage.getItem(key())||'[]')||[]).map(normalize)}catch(_){return []}}
function localSave(){localStorage.setItem(key(),JSON.stringify(drafts))}
function total(d=current){return (d?.items||[]).reduce((n,x)=>n+Number(x.qty||0)*Number(x.unitPrice||0),0)}
function money(n){return `RM ${Number(n||0).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
async function load(){const client=window.KeySuiteAuth?.getClient?.();if(client){try{const {data,error}=await client.rpc('keysuite_list_assemblies_v201');if(error)throw error;drafts=(data||[]).map(normalize);loaded=true;localSave();return}catch(e){console.warn('Assembly V2.01 Supabase fallback',e)}}drafts=localLoad();loaded=true}
async function persist(d){d.updated_at=new Date().toISOString();const client=window.KeySuiteAuth?.getClient?.();if(client){const {data,error}=await client.rpc('keysuite_save_assembly_v201',{p_assembly:d});if(error)throw error;const saved=Array.isArray(data)?data[0]:data;if(saved)d=normalize({...d,...saved,items:saved.items||d.items})}const i=drafts.findIndex(x=>x.id===d.id);if(i>=0)drafts[i]=d;else drafts.unshift(d);current=d;localSave();return d}
async function remove(){if(!current||!confirm(`Delete ${current.name}?`))return;const client=window.KeySuiteAuth?.getClient?.();if(client){const {error}=await client.rpc('keysuite_delete_assembly_v200',{p_assembly_id:current.id});if(error)throw error}drafts=drafts.filter(x=>x.id!==current.id);localSave();current=drafts.find(x=>x.assembly_type===type)||blank();render()}
function read(){if(!current)return;current.model_item=$('assemblyModelItem')?.value.trim()||'';current.description=$('assemblyDescription')?.value||'';current.name=current.model_item||current.name||(`New ${type==='system'?'System':'Pumpset'}`);current.customer_id=quoteCustomerId()||current.customer_id||'';current.status=$('assemblyStatus')?.value||current.status||'draft';document.querySelectorAll('[data-assembly-item]').forEach(row=>{const item=current.items.find(x=>x.id===row.dataset.assemblyItem);if(item){item.qty=Math.max(0,Number(row.querySelector('.assembly-qty').value)||0);item.unitPrice=Math.max(0,Number(row.querySelector('.assembly-price').value)||0)}})}
function renderList(){const list=$('assemblyDraftList');if(!list)return;const rows=drafts.filter(x=>x.assembly_type===type);list.innerHTML=rows.map(d=>`<button type="button" class="${d.id===current?.id?'active':''}" data-draft="${esc(d.id)}"><b>${esc(d.model_item||d.name)}</b><br><small>${esc(d.status)} · ${money(total(d))}</small></button>`).join('')||'<div class="muted">No saved drafts.</div>';list.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>{current=drafts.find(x=>x.id===b.dataset.draft);render()})}
function itemHtml(x){return `<div class="assembly-item" data-assembly-item="${esc(x.id)}"><div><b>${esc(x.bomDescription||x.model)}</b></div><div><label>Qty</label><input class="assembly-qty" type="number" min="0" step="1" value="${Number(x.qty||1)}"></div><div><label>Unit Price</label><input class="assembly-price" type="number" min="0" step="0.01" value="${Number(x.unitPrice||0).toFixed(2)}"></div><div><label>Total Price</label><div class="assembly-line-total">${money(Number(x.qty||0)*Number(x.unitPrice||0))}</div></div><button class="btn danger assembly-delete" type="button">Delete</button></div>`}
function renderItems(){const box=$('assemblyItems');if(!box)return;box.innerHTML=sections[type].map(section=>{const rows=(current?.items||[]).filter(x=>x.section===section);return `<section class="assembly-section"><div class="assembly-section-head"><h2>${labels[section]}</h2><span>${rows.length} item${rows.length===1?'':'s'}</span></div><div class="assembly-section-body">${rows.map(itemHtml).join('')||'<p class="muted assembly-empty">Empty</p>'}</div></section>`}).join('');box.querySelectorAll('input').forEach(i=>i.oninput=()=>{read();renderItems();$('assemblyTotal').textContent=money(total())});box.querySelectorAll('.assembly-delete').forEach(b=>b.onclick=()=>{const row=b.closest('[data-assembly-item]');current.items=current.items.filter(x=>x.id!==row.dataset.assemblyItem);renderItems()});$('assemblyTotal').textContent=money(total())}
function render(){if(!current||current.assembly_type!==type)current=drafts.find(x=>x.assembly_type===type)||blank(type);current=normalize(current);const qCustomer=quoteCustomerId();if(qCustomer)current.customer_id=qCustomer;$('assemblyBuilderTitle').textContent=type==='system'?'System':'Pumpset';$('assemblyModelItem').value=current.model_item||'';$('assemblyDescription').value=current.description||'';$('assemblyDescriptionLabel').textContent=type==='system'?'System Description':'Pumpset Description';$('assemblyCustomer').innerHTML='<option value="">No quotation customer selected</option>'+customers().map(c=>`<option value="${esc(c.id)}">${esc(c.company)}</option>`).join('');$('assemblyCustomer').value=current.customer_id||'';$('assemblyCustomer').disabled=true;if($('assemblyStatus'))$('assemblyStatus').value=current.status||'draft';$('assemblyNotice').textContent=qCustomer?'Customer is locked to the active Quotation selection. Descriptions sent from Selector or Product are placed into the Assembly description.':'Select a customer in Quotation first. Assembly customer cannot be entered manually.';renderList();renderItems()}
async function open(t){type=t;window.KeySuiteApp?.showPage?.('assemblyBuilder');if(!loaded)await load();current=drafts.find(x=>x.assembly_type===type&&x.status==='draft')||drafts.find(x=>x.assembly_type===type)||blank(type);render()}
async function save(){read();try{await persist(current);render();$('assemblyNotice').textContent=`${current.model_item||current.name} saved.`}catch(e){alert(`Assembly could not be saved: ${e.message||e}`)}}
function routeItem(item={}){const level=String(item.assemblyLevel||item.assembly_level||'').toUpperCase();const section=String(item.assemblySection||item.assembly_section||'').toLowerCase();if(level==='COMPLETE_PUMPSET'||section==='pumpset')return {type:'system',section:'pumpset'};if(['pump','motor','coupling','baseplate'].includes(section))return {type:'pumpset',section};if(['control_panel','manifold','tank','misc'].includes(section))return {type:'system',section};const model=String(item.model||'');if(/^CHC\b/i.test(model))return {type:'system',section:'pumpset'};if(/^ES\b/i.test(model))return {type:'pumpset',section:'pump'};if(/tank|gws/i.test(model+' '+(item.description||'')))return {type:'system',section:'tank'};return {type:'system',section:'misc'}}
function addItem(item,explicitRoute){const route=explicitRoute||routeItem(item);const customerId=quoteCustomerId();if(!customerId){alert('Select the customer in Quotation first. Assembly follows the Quotation customer and cannot be filled manually.');window.KeySuiteApp?.showPage?.('quotation');return}type=route.type;const target=drafts.find(x=>x.assembly_type===type&&x.status==='draft'&&x.customer_id===customerId)||blank(type);if(!drafts.some(x=>x.id===target.id))drafts.unshift(target);target.customer_id=customerId;const description=String(item.description||'').trim();if(description){target.description=target.description?`${target.description}\n\n${description}`:description}if(type==='pumpset'&&route.section==='pump'&&!target.model_item)target.model_item=item.model||'';target.items.push({id:uid(),section:route.section,model:item.model||'Product',bomDescription:item.bomDescription||item.model||'Product',description,qty:Number(item.qty||1),unitPrice:Number(item.unitPrice||0),pricingSource:item.pricingSource||null,pumpData:item.pumpData||null});current=target;localSave();open(type);$('assemblyNotice').textContent=`${item.model||'Product'} routed to ${type==='system'?'System':'Pumpset'} → ${labels[route.section]}. Its quotation description was transferred to the ${type==='system'?'System':'Pumpset'} Description.`;}
function toQuotation(){read();if(!current?.items?.length){alert('Add at least one component first.');return}if(!current.customer_id){alert('Select a customer for this assembly.');return}window.KeySuiteApp?.selectCustomerForQuotation?.(current.customer_id);window.KeySuiteApp?.showPage?.('quotation');const componentText=sections[type].map(s=>{const xs=current.items.filter(x=>x.section===s);return xs.length?`${labels[s]}:\n${xs.map(x=>`• ${x.model} × ${x.qty}`).join('\n')}`:''}).filter(Boolean).join('\n\n');const description=[current.description,componentText].filter(Boolean).join('\n\n');const row=window.KeySuiteApp?.addExternalQuoteItem?.({model:current.model_item||current.name||'',qty:1,unitPrice:total(),description});if(!row){alert('Unable to add the assembly to Quotation.');return}current.status='quoted';save()}
function pageShown(id){if(id==='assemblyBuilder'&&loaded)render()}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-assembly-open]').forEach(b=>b.onclick=()=>open(b.dataset.assemblyOpen));$('newAssemblyDraft')?.addEventListener('click',()=>{current=blank(type);render()});$('saveAssemblyDraft')?.addEventListener('click',save);$('deleteAssemblyDraft')?.addEventListener('click',()=>remove().catch(e=>alert(e.message||e)));$('assemblyToQuotation')?.addEventListener('click',toQuotation);const main=$('assemblyDescription'),dlg=$('assemblyDescriptionDialog'),popup=$('assemblyDescriptionPopup');main?.addEventListener('dblclick',()=>{popup.value=main.value;dlg.showModal()});$('saveAssemblyDescriptionPopup')?.addEventListener('click',()=>{main.value=popup.value;read()})});
window.KeySuiteAssembly={open,addItem,routeItem,pageShown};
})();
